title: Hello, world! I'm Hanaa Charania
permalink: ':title/'
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Hanaa Charania # add your name
author-img: Hanaa Charania - Photo.JPG # add your photo
about-author: Computer Science & Spanish Double Major at Amherst College # add description
social-github: hanaacharania # add your Github handle
social-linkedin: hanaa-charania # add your Linkedin handle
social-email: hcharania25@amherst.edu # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
